config/routes.rb
Rails.application.routes.draw do

  # the page root
  root 'users#edit'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :admin_sessions, only: [:create]
    resources :admin_users, only: [:show]
    resources :twilio do
      collection do 
        get :confirm_coach
        get :confirm_user
        post :call_ended_coach
        post :call_ended_user
        get :end_user
        get :end_coach
        get :hold_coach
        get :hold_user
        get :after_confirmation_user
        get :after_confirmation_coach
        get :join_coach
        get :join_user
        get :rejoin_coach
        get :rejoin_user
        get :hold_user_after_joined
        get :hold_coach_after_joined
        get :finished_session_coach
        get :submit_review
        get :after_first_review_enter
        get :invalid_first_grade
        get :submit_second_grade
        get :after_second_review_enter
        get :invalid_second_grade
      end
    end
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  resources :coaching_dates do
    member do
      post :pay_with_credit_card
    end
  end

  resources :coaches do 
    member do
      get :set_coaching_dates
      get :financial_details
      get :verify_phone
      post :set_financial_details
      post :add_coaching_dates
      post :remove_coaching_dates
      post :verify_token
      post :resend_code
    end
    collection do
      get :show_coaches
    end
  end

  resources :clients do
    member do
      get :verify_phone
      post :verify_token
      post :resend_code
    end
  end

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
    post 'sign_in_from_admin' => 'users#sign_in_from_admin'
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  belongs_to :user
  has_many :coaching_dates
  has_many :payments
  has_many :reviews
  mount_uploader :photo, ImageUploader
  #validates_inclusion_of :rate, in: 10..200


  def name
    return (self.first_name.present? ? self.first_name : "")  + " " + (self.last_name.present? ? self.last_name : "")
  end

  def self.available
    Coach.all.select{|c| c.coaching_dates.upcoming.available.present?}
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def edit
    @coach = Coach.find(params[:id])
  end

  def update
    @coach = Coach.find(params[:id])
    success = true
    if @coach.phone != coach_params[:phone]
      token = 4.times.map{rand(10)}.join
      success = SendTwilioMessage.send_message(coach_params[:phone], token)
      @coach.validated_phone = false
      @coach.phone_code = token
      @coach.save
    end
    if @coach.update(coach_params)
      if success 
        flash[:notice] = "Profile successfully updated!"
      else
        flash[:notice] = "Invalid phone number. Please provide a valid one!"
      end
    elsif !success
      flash[:notice] = "Invalid phone number. Please provide a valid one!"
    else
      flash[:notice] = "Error while updating profile. Please try again!"
    end
    redirect_to :back
  end

  def show
    @coach = Coach.find(params[:id])
    @coaching_dates = @coach.coaching_dates.upcoming.available
    @average = @coach.reviews.map{|r| r.coach_grade}.inject{ |sum, el| sum + el }.to_f / @coach.reviews.count
    @average_rating = @coach.reviews.present? ? "#{@average.round(2)}/5" : "N/A"
  end

  def set_coaching_dates
    @coach = Coach.find(params[:id])
    authorize! :coaching_dates, @coach
    @coaching_dates = @coach.coaching_dates.upcoming
  end

  def financial_details
    @coach = Coach.find(params[:id])
  end

  def set_financial_details
    @coach = Coach.find(params[:id])
    authorize! :coaching_dates, @coach
    @coach.rate = params[:rate]
    if @coach.save
      flash[:notice] = "Rate successfully updated!"
      redirect_to set_coaching_dates_coach_path(@coach)
    else
      flash[:motice] = "Error while setting rate. Please try again!"
      redirect_to :back
    end
  end

  def add_coaching_dates
    @coach = Coach.find(params[:id])
    starting = DateTime.strptime(params[:date] + " " + params[:starting_hour].to_s + ":" +params[:starting_minutes].to_s + " "+ params[:starting_am], "%m/%d/%Y %l:%M %p")
    ending = DateTime.strptime(params[:date] + " " + params[:ending_hour].to_s + ":" +params[:ending_minutes].to_s + " "+ params[:ending_am], "%m/%d/%Y %l:%M %p")
    if starting < ending
      while starting < ending
        if @coach.coaching_dates.where(starting: starting).limit(1).blank?
          c = CoachingDate.new
          c.starting = starting
          c.coach = @coach
          c.duration = 30
          c.paid_duration = 20  
          c.save
        end
        starting += 30.minutes
      end
      flash[:notice] = "Coaching dates successfully added!"
    else
      flash[:notice] = "Starting time cannot be before ending time!"
    end

    redirect_to :back
  end

  def remove_coaching_dates
    @coach = Coach.find(params[:id])
    starting = DateTime.strptime(params[:date] + " " + params[:starting_hour].to_s + ":" +params[:starting_minutes].to_s + " "+ params[:starting_am], "%m/%d/%Y %l:%M %p")
    ending = DateTime.strptime(params[:date] + " " + params[:ending_hour].to_s + ":" +params[:ending_minutes].to_s + " "+ params[:ending_am], "%m/%d/%Y %l:%M %p")
    if starting < ending
      @coach.coaching_dates.available.where("starting >= ? AND starting <= ?", starting, ending).destroy_all
      flash[:notice] = "Coaching dates successfully destroyed!"
    else
      flash[:notice] = "Starting time cannot be before ending time!"
    end

    redirect_to :back
  end

  def show_coaches
    @coaches = Coach.available
    @average_rating = {}
    @coaches.each do |coach|
      average = coach.reviews.map{|r| r.coach_grade}.inject{ |sum, el| sum + el }.to_f / coach.reviews.count
      @average_rating[coach] = coach.reviews.present? ? "#{average.round(2)}/5" : "N/A"
    end
  end

  def verify_phone
    @coach = Coach.find(params[:id])
  end

  def verify_token
    token = params[:token]
    coach = Coach.find(params[:id])
    if token == coach.phone_code
      coach.validated_phone = true
      coach.save
      flash[:notice] = "Phone successfully verified!"
      redirect_to edit_coach_path(coach)
    else
      flash[:notice] = "Incorrect code. Please try again!"
      redirect_to :back
    end
  end

  def resend_code
    @coach = Coach.find(params[:id])
    token = 4.times.map{rand(10)}.join
    @coach.phone_code = token
    @coach.save
    success = SendTwilioMessage.send_message(@coach.phone, token)
    if success
      flash[:notice] = "Code successfully resent!"
      redirect_to :back
    else
      flash[:notice] = "Invalid phone number. Please provide a valid one!"
      redirect_to edit_coach_path(@coach)
    end
  end

  private
  def coach_params
    params.require(:coach).permit(:first_name, :last_name, :about, :occupation, :phone)
  end
end

app/views/coaches/partials/_booking_dates.html.haml
.card
  .card-header
    %strong Coaching Dates
  .card-block
    - if @coaching_dates.present?
      - @coaching_dates.each do |cd|
        .col-lg-10
          %h5
            = cd.starting.strftime("%m/%d/%Y - from %l:%M %p")
        - if current_user.account_type == "client"
          .col-lg-2
            = link_to "Book", edit_coaching_date_path(cd), class: "btn btn-primary"
        %br
        %br
    - else
      %h5.text-center
        = "No coaching sessions are available right now. Please try again later."

app/views/coaches/partials/_coach_profile.html.haml
.card
  .card-block
    .text-center
      = image_tag coach.user.image, class: "coach_image"
      %br
      %br
      %h2.name_text
        = coach.name 
      %h5.occupation_text
        = coach.occupation
      %h6
        = "Average rating: #{average_rating}"
      %br
      %h6
        = coach.about

app/views/coaches/partials/_coach_tile.html.haml
.col-lg-3
  = link_to coach_path(coach), class: "no_decoration" do
    = render "coaches/partials/coach_profile", coach: coach, average_rating: @average_rating[coach]
  / .card
  /   .card-block
  /     .text-center
  /       = image_tag coach.user.image, class: "coach_image"
  /       %br
  /       %br
  /       %h2.name_text
  /         = coach.name 
  /       %h5.occupation_text
  /         = coach.occupation
  /       %h6
  /         = "Average rating: #{@average_rating}"
  /       %br
  /       %h6
  /         = coach.about
  /       = link_to "#{coach.name}", coach_path(coach)

app/views/coaches/partials/_set_coaching_dates.html.haml
= form_tag add_coaching_dates_coach_path(@coach), method: :post do
  .card
    .card-header
      %strong Add coaching dates
    .card-block
      .form-group.row
        .col-lg-2
          = label_tag :date, "Date" 
        .col-lg-10
          = text_field_tag :date, "", autocomplete: "off", class: "datepicker form-control", required: true

      .form-group.row
        .col-lg-3
          = label_tag :starting_hour, "Starting time: "  
        .col-lg-3
          = select_tag :starting_hour, options_for_select(["1","2","3","4","5","6","7","8","9","10","11","12"], "9"), {class: "form-control"}
        .col-lg-3
          = select_tag :starting_minutes, options_for_select(["00","30"], "00"), {class: "form-control"}
        .col-lg-3
          = select_tag :starting_am, options_for_select(["AM", "PM"], "AM"), {class: "form-control"}


      .form-group.row
        .col-lg-3
          = label_tag :ending_hour, "Ending time: "  
        .col-lg-3
          = select_tag :ending_hour, options_for_select(["1","2","3","4","5","6","7","8","9","10","11","12"], "5"), {class: "form-control"}
        .col-lg-3
          = select_tag :ending_minutes, options_for_select(["00","30"]), {class: "form-control"}
        .col-lg-3
          = select_tag :ending_am, options_for_select(["AM", "PM"], "PM"), {selected: "PM", class: "form-control"}


    .card-footer.text-center
      = submit_tag "Add", class: "btn btn-sm btn-primary"

%br
%br

= form_tag remove_coaching_dates_coach_path(@coach), method: :post do
  .card
    .card-header
      %strong Remove coaching dates
    .card-block
      .form-group.row
        .col-lg-2
          = label_tag :date, "Date" 
        .col-lg-10
          = text_field_tag :date, "", autocomplete: "off", class: "datepicker form-control", required: true

      .form-group.row
        .col-lg-3
          = label_tag :starting_hour, "Starting time: "  
        .col-lg-3
          = select_tag :starting_hour, options_for_select(["1","2","3","4","5","6","7","8","9","10","11","12"], "9"), {class: "form-control"}
        .col-lg-3
          = select_tag :starting_minutes, options_for_select(["00","30"], "00"), {class: "form-control"}
        .col-lg-3
          = select_tag :starting_am, options_for_select(["AM", "PM"], "AM"), {class: "form-control"}


      .form-group.row
        .col-lg-3
          = label_tag :ending_hour, "Ending time: "  
        .col-lg-3
          = select_tag :ending_hour, options_for_select(["1","2","3","4","5","6","7","8","9","10","11","12"], "5"), {class: "form-control"}
        .col-lg-3
          = select_tag :ending_minutes, options_for_select(["00","30"]), {class: "form-control"}
        .col-lg-3
          = select_tag :ending_am, options_for_select(["AM", "PM"], "PM"), {selected: "PM", class: "form-control"}


    .card-footer.text-center
      = submit_tag "Remove", class: "btn btn-sm btn-danger"

:javascript
  window.starterkitrails.shared.initDatePicker("#{Date.today.strftime("%m-%d-%Y")}");

app/views/coaches/partials/_show_coaching_date.html.haml
.col-lg-10
  %h5
    = cd.starting.strftime("%m/%d/%Y - from %l:%M %p")
.col-lg-2
  %h6
    - if cd.client_id.blank?
      = link_to "Delete", coaching_date_path(cd), method: :delete, class: "btn btn-danger"

    - else
      = "booked by #{cd.client.name}"

app/views/coaches/partials/_view_coaching_dates.html.haml
.card
  .card-header
    %strong Coaching Dates
  .card-block
    - if @coaching_dates.present?
      - @coaching_dates.each do |cd|
        = render "coaches/partials/show_coaching_date", cd: cd
    - else
      %h4
        = "You have no coaching dates."