config/routes.rb
Rails.application.routes.draw do

  # the page root
  root 'users#edit'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :admin_sessions, only: [:create]
    resources :admin_users, only: [:show]
    resources :twilio do
      collection do 
        get :confirm_coach
        get :confirm_user
        post :call_ended_coach
        post :call_ended_user
        get :end_user
        get :end_coach
        get :hold_coach
        get :hold_user
        get :after_confirmation_user
        get :after_confirmation_coach
        get :join_coach
        get :join_user
        get :rejoin_coach
        get :rejoin_user
        get :hold_user_after_joined
        get :hold_coach_after_joined
        get :finished_session_coach
        get :submit_review
        get :after_first_review_enter
        get :invalid_first_grade
        get :submit_second_grade
        get :after_second_review_enter
        get :invalid_second_grade
      end
    end
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  resources :coaching_dates do
    member do
      post :pay_with_credit_card
    end
  end

  resources :coaches do 
    member do
      get :set_coaching_dates
      get :financial_details
      get :verify_phone
      post :set_financial_details
      post :add_coaching_dates
      post :remove_coaching_dates
      post :verify_token
      post :resend_code
    end
    collection do
      get :show_coaches
    end
  end

  resources :clients do
    member do
      get :verify_phone
      post :verify_token
      post :resend_code
    end
  end

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
    post 'sign_in_from_admin' => 'users#sign_in_from_admin'
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/views/shared/_flash_notice.html.haml
- if flash[:notice].present? || flash[:alert].present? || flash[:error].present?
  - [:notice, :alert, :error].each do |key|
    - next if flash[key].blank?
    .flash-container
      .flash{class: key}
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
        = flash[key]

      - flash[key] = nil

app/views/shared/_header.html.haml
%button.navbar-toggler.mobile-sidebar-toggler.d-lg-none{:type => "button"} ☰
%h3.app_logo
  = link_to "Coaching App", root_url
%ul.nav.navbar-nav.d-md-down-none
  %li.nav-item
    %a.nav-link.navbar-toggler.sidebar-toggler{:href => "#"} ☰
%ul.nav.navbar-nav.ml-auto
  - if current_user.account_type == "client"
    %li.nav-item.d-md-down-none
      %a.nav-link{:href => "#"}
        %i.icon-credit-card.bigger_money
        %span.badge.badge-pill.badge-danger.bigger_tokens #{current_user.client.tokens}

  %li.nav-item.dropdown
    %a.nav-link.dropdown-toggle.nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
      = image_tag current_user.image, class: "img-avatar"
      %span.d-md-down-none #{current_user.email}
    .dropdown-menu.dropdown-menu-right
      .dropdown-header.text-center
        %strong Account
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-bell-o
        Updates
        %span.badge.badge-info 42
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-envelope-o
        Messages
        %span.badge.badge-success 42
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-tasks
        Tasks
        %span.badge.badge-danger 42
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-comments
        Comments
        %span.badge.badge-warning 42
      .dropdown-header.text-center
        %strong Settings
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-user
        Profile
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-wrench
        Settings
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-usd
        Payments
        %span.badge.badge-default 42
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-file
        Projects
        %span.badge.badge-primary 42
      .divider
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-shield
        Lock Account
      %a.dropdown-item{:href => "#"}
        %i.fa.fa-lock
        Logout

app/views/shared/_languages.html.haml
= link_to_unless_current "En", sessions_path("en")

app/views/shared/_logo.html.haml
.form-group
  %i.fa.fa-star
  STARTER-KIT

app/views/shared/_nav.html.haml
%ul.nav
  %li.nav-title
    = "#{current_user.account_type.capitalize} Area" 
  
  - if current_user.account_type == "coach"
    %li.nav-item
      = link_to coach_path(current_user.coach), class: "nav-link" do
        %i.icon-user
        View Profile

    %li.nav-item
      = link_to edit_coach_path(current_user.coach), class: "nav-link" do
        %i.icon-envelope-letter
        Edit Coach Profile

    - if current_user.coach.name.present? && current_user.coach.phone.present? && current_user.coach.validated_phone
      %li.nav-item
        = link_to set_coaching_dates_coach_path(current_user.coach), class: "nav-link" do
          %i.icon-clock
          Set sessions

      %li.nav-item
        = link_to financial_details_coach_path(current_user.coach), class: "nav-link" do
          %i.icon-wallet
          Financial details
  - else
    %li.nav-item
      = link_to edit_client_path(current_user.client), class: "nav-link" do
        %i.icon-envelope-letter
        Edit Client Profile
    - if current_user.client.name.present? && current_user.client.phone.present? && current_user.client.validated_phone
      %li.nav-item
        = link_to show_coaches_coaches_path, class: "nav-link" do
          %i.icon-clock
          Book session
  %li.nav-title
    Account settings
    %li.nav-item
      = link_to edit_user_path(current_user), class: "nav-link" do
        %i.icon-settings
        Account Settings

  %li.nav-title
    Log out
    %li.nav-item
      = link_to signout_path, class: "nav-link" do
        %i.icon-logout
        Logout