config/routes.rb
Rails.application.routes.draw do

  # the page root
  root 'users#edit'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :admin_sessions, only: [:create]
    resources :admin_users, only: [:show]
    resources :twilio do
      collection do 
        get :confirm_coach
        get :confirm_user
        post :call_ended_coach
        post :call_ended_user
        get :end_user
        get :end_coach
        get :hold_coach
        get :hold_user
        get :after_confirmation_user
        get :after_confirmation_coach
        get :join_coach
        get :join_user
        get :rejoin_coach
        get :rejoin_user
        get :hold_user_after_joined
        get :hold_coach_after_joined
        get :finished_session_coach
        get :submit_review
        get :after_first_review_enter
        get :invalid_first_grade
        get :submit_second_grade
        get :after_second_review_enter
        get :invalid_second_grade
      end
    end
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  resources :coaching_dates do
    member do
      post :pay_with_credit_card
    end
  end

  resources :coaches do 
    member do
      get :set_coaching_dates
      get :financial_details
      get :verify_phone
      post :set_financial_details
      post :add_coaching_dates
      post :remove_coaching_dates
      post :verify_token
      post :resend_code
    end
    collection do
      get :show_coaches
    end
  end

  resources :clients do
    member do
      get :verify_phone
      post :verify_token
      post :resend_code
    end
  end

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
    post 'sign_in_from_admin' => 'users#sign_in_from_admin'
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :coaching_dates
  has_many :balance_logs
  has_many :payments
  has_many :reviews
  mount_uploader :photo, ImageUploader

  def name
    return self.first_name + " " + self.last_name
  end

  def name_with_email
    return self.name + " - " + self.user.email
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def edit 
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    success = true
    if @client.phone != client_params[:phone]
      token = 4.times.map{rand(10)}.join
      success = SendTwilioMessage.send_message(client_params[:phone], token)
      @client.validated_phone = false
      @client.phone_code = token
      @client.save
    end
    if @client.update(client_params)
      if success 
        flash[:notice] = "Profile successfully updated!"
      else
        flash[:notice] = "Invalid phone number. Please provide a valid one!"
      end
    else
      flash[:notice] = "Error while updating profile. Please try again!"
    end
    redirect_to :back
  end

  def verify_phone
    @client = Client.find(params[:id])
  end

  def resend_code
    @client = Client.find(params[:id])
    token = 4.times.map{rand(10)}.join
    @client.phone_code = token
    @client.save
    success = SendTwilioMessage.send_message(@client.phone, token)
    if success
      flash[:notice] = "Code successfully resent!"
      redirect_to :back
    else
      flash[:notice] = "Invalid phone number. Please provide a valid one!"
      redirect_to edit_client_path(@client)
    end
  end

  def verify_token
    token = params[:token]
    client = Client.find(params[:id])
    if token == client.phone_code
      client.validated_phone = true
      client.save
      flash[:notice] = "Phone successfully verified!"
      redirect_to edit_client_path(client)
    else
      flash[:notice] = "Incorrect code. Please try again!"
      redirect_to :back
    end
  end

  private 
  def client_params
    params.require(:client).permit(:first_name, :last_name, :about, :occupation, :phone)
  end
end

app/views/clients/edit.html.haml
.row.pager
  .col-md-12

    = form_for @client, url: client_path(@client), method: :patch do |f|
      //- add_error(resource.errors.full_messages.to_sentence, 'alert') if resource.errors.present?
      .col-lg-6.col-lg-offset-3
        .card
          .card-header
            %strong Client Profile
          .card-block
            .form-group
            .form-group.row
              .col-md-3
                = f.label :first_name, "First Name", class: "form-control-label"
              .col-md-9
                = f.text_field :first_name, autofocus: true, autocomplete: "off", required:true, placeholder: "First name", class: "form-control input-text"

            .form-group.row
              .col-md-3
                = f.label :last_name, "Last Name", class: "form-control-label"
              .col-md-9
                = f.text_field :last_name, autofocus: true, autocomplete: "off", required:true, placeholder: "Last name", class: "form-control input-text"

            .form-group.row
              .col-md-3
                = f.label :occupation, "Occupation", class: "form-control-label"
              .col-md-9
                = f.text_field :occupation, autofocus: true, autocomplete: "off", required:true, placeholder: "Occupation", class: "form-control input-text"

            .form-group.row
              .col-md-3
                = f.label :phone, "Phone number", class: "form-control-label"
              .col-md-9
                = f.text_field :phone, autofocus: true, autocomplete: "off", required:true, placeholder: "Phone", class: "form-control input-text"

            .form-group.row
              .col-md-3
                = f.label :about, "About me", class: "form-control-label"
              .col-md-9
                = f.text_area :about, placeholder: "About", rows: 4, class: "form-control"

            -if @client.phone.blank?
              .verify_phone
                = 'Please fill in your profile.'
            - elsif !@client.validated_phone
              .form-group.row
                .col-md-12
                  = link_to 'Please verify your phone number in order to use the application.', verify_phone_client_path(@client), class: "verify_phone"

          .card-footer
            = f.submit "Update", class: "btn btn-sm btn-primary"

app/views/clients/verify_phone.html.haml
.row.pager
  .col-md-12

    = form_tag verify_token_client_path(@client), method: :post do |f|
      //- add_error(resource.errors.full_messages.to_sentence, 'alert') if resource.errors.present?
      .col-lg-6.col-lg-offset-3
        .card
          .card-header
            %strong Enter received token
          .card-block
            .form-group.row
              .col-md-12
                = "Please enter the token code receive on your phone."
                

            .form-group.row
              .col-md-3
                = label_tag 'token', "Received token", class: "form-control-label"
              .col-md-9
                = text_field_tag 'token', nil ,required: true, placeholder: "Token", class: "form-control input-text"

            %br
            .form-group.row
              .col-md-12
                = "Didn't receive confirmation token? Click "
                = link_to "here", resend_code_client_path(@client), method: :post
                = " to resend." 

          .card-footer
            = submit_tag "Verify", class: "btn btn-sm btn-primary"