config/routes.rb
Rails.application.routes.draw do

  # the page root
  root 'users#edit'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
  namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
    mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :admin_sessions, only: [:create]
    resources :admin_users, only: [:show]
    resources :twilio do
      collection do 
        get :confirm_coach
        get :confirm_user
        post :call_ended_coach
        post :call_ended_user
        get :end_user
        get :end_coach
        get :hold_coach
        get :hold_user
        get :after_confirmation_user
        get :after_confirmation_coach
        get :join_coach
        get :join_user
        get :rejoin_coach
        get :rejoin_user
        get :hold_user_after_joined
        get :hold_coach_after_joined
        get :finished_session_coach
        get :submit_review
        get :after_first_review_enter
        get :invalid_first_grade
        get :submit_second_grade
        get :after_second_review_enter
        get :invalid_second_grade
      end
    end
  end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  resources :coaching_dates do
    member do
      post :pay_with_credit_card
    end
  end

  resources :coaches do 
    member do
      get :set_coaching_dates
      get :financial_details
      get :verify_phone
      post :set_financial_details
      post :add_coaching_dates
      post :remove_coaching_dates
      post :verify_token
      post :resend_code
    end
    collection do
      get :show_coaches
    end
  end

  resources :clients do
    member do
      get :verify_phone
      post :verify_token
      post :resend_code
    end
  end

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
    post 'sign_in_from_admin' => 'users#sign_in_from_admin'
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  belongs_to :user
  has_many :coaching_dates
  has_many :payments
  has_many :reviews
  mount_uploader :photo, ImageUploader
  #validates_inclusion_of :rate, in: 10..200


  def name
    return (self.first_name.present? ? self.first_name : "")  + " " + (self.last_name.present? ? self.last_name : "")
  end

  def self.available
    Coach.all.select{|c| c.coaching_dates.upcoming.available.present?}
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def edit
    @coach = Coach.find(params[:id])
  end

  def update
    @coach = Coach.find(params[:id])
    success = true
    if @coach.phone != coach_params[:phone]
      token = 4.times.map{rand(10)}.join
      success = SendTwilioMessage.send_message(coach_params[:phone], token)
      @coach.validated_phone = false
      @coach.phone_code = token
      @coach.save
    end
    if @coach.update(coach_params)
      if success 
        flash[:notice] = "Profile successfully updated!"
      else
        flash[:notice] = "Invalid phone number. Please provide a valid one!"
      end
    elsif !success
      flash[:notice] = "Invalid phone number. Please provide a valid one!"
    else
      flash[:notice] = "Error while updating profile. Please try again!"
    end
    redirect_to :back
  end

  def show
    @coach = Coach.find(params[:id])
    @coaching_dates = @coach.coaching_dates.upcoming.available
    @average = @coach.reviews.map{|r| r.coach_grade}.inject{ |sum, el| sum + el }.to_f / @coach.reviews.count
    @average_rating = @coach.reviews.present? ? "#{@average.round(2)}/5" : "N/A"
  end

  def set_coaching_dates
    @coach = Coach.find(params[:id])
    authorize! :coaching_dates, @coach
    @coaching_dates = @coach.coaching_dates.upcoming
  end

  def financial_details
    @coach = Coach.find(params[:id])
  end

  def set_financial_details
    @coach = Coach.find(params[:id])
    authorize! :coaching_dates, @coach
    @coach.rate = params[:rate]
    if @coach.save
      flash[:notice] = "Rate successfully updated!"
      redirect_to set_coaching_dates_coach_path(@coach)
    else
      flash[:motice] = "Error while setting rate. Please try again!"
      redirect_to :back
    end
  end

  def add_coaching_dates
    @coach = Coach.find(params[:id])
    starting = DateTime.strptime(params[:date] + " " + params[:starting_hour].to_s + ":" +params[:starting_minutes].to_s + " "+ params[:starting_am], "%m/%d/%Y %l:%M %p")
    ending = DateTime.strptime(params[:date] + " " + params[:ending_hour].to_s + ":" +params[:ending_minutes].to_s + " "+ params[:ending_am], "%m/%d/%Y %l:%M %p")
    if starting < ending
      while starting < ending
        if @coach.coaching_dates.where(starting: starting).limit(1).blank?
          c = CoachingDate.new
          c.starting = starting
          c.coach = @coach
          c.duration = 30
          c.paid_duration = 20  
          c.save
        end
        starting += 30.minutes
      end
      flash[:notice] = "Coaching dates successfully added!"
    else
      flash[:notice] = "Starting time cannot be before ending time!"
    end

    redirect_to :back
  end

  def remove_coaching_dates
    @coach = Coach.find(params[:id])
    starting = DateTime.strptime(params[:date] + " " + params[:starting_hour].to_s + ":" +params[:starting_minutes].to_s + " "+ params[:starting_am], "%m/%d/%Y %l:%M %p")
    ending = DateTime.strptime(params[:date] + " " + params[:ending_hour].to_s + ":" +params[:ending_minutes].to_s + " "+ params[:ending_am], "%m/%d/%Y %l:%M %p")
    if starting < ending
      @coach.coaching_dates.available.where("starting >= ? AND starting <= ?", starting, ending).destroy_all
      flash[:notice] = "Coaching dates successfully destroyed!"
    else
      flash[:notice] = "Starting time cannot be before ending time!"
    end

    redirect_to :back
  end

  def show_coaches
    @coaches = Coach.available
    @average_rating = {}
    @coaches.each do |coach|
      average = coach.reviews.map{|r| r.coach_grade}.inject{ |sum, el| sum + el }.to_f / coach.reviews.count
      @average_rating[coach] = coach.reviews.present? ? "#{average.round(2)}/5" : "N/A"
    end
  end

  def verify_phone
    @coach = Coach.find(params[:id])
  end

  def verify_token
    token = params[:token]
    coach = Coach.find(params[:id])
    if token == coach.phone_code
      coach.validated_phone = true
      coach.save
      flash[:notice] = "Phone successfully verified!"
      redirect_to edit_coach_path(coach)
    else
      flash[:notice] = "Incorrect code. Please try again!"
      redirect_to :back
    end
  end

  def resend_code
    @coach = Coach.find(params[:id])
    token = 4.times.map{rand(10)}.join
    @coach.phone_code = token
    @coach.save
    success = SendTwilioMessage.send_message(@coach.phone, token)
    if success
      flash[:notice] = "Code successfully resent!"
      redirect_to :back
    else
      flash[:notice] = "Invalid phone number. Please provide a valid one!"
      redirect_to edit_coach_path(@coach)
    end
  end

  private
  def coach_params
    params.require(:coach).permit(:first_name, :last_name, :about, :occupation, :phone)
  end
end

app/views/coaches/edit.html.haml
.row.pager
  .col-md-12

    = form_for @coach, url: coach_path(@coach), method: :patch do |f|
      //- add_error(resource.errors.full_messages.to_sentence, 'alert') if resource.errors.present?
      .col-lg-6.col-lg-offset-3
        .card
          .card-header
            %strong Coach Profile
          .card-block
            .form-group
            .form-group.row
              .col-md-3
                = f.label :first_name, "First Name", class: "form-control-label"
              .col-md-9
                = f.text_field :first_name, autofocus: true, autocomplete: "off", required:true, placeholder: "First name", class: "form-control input-text"

            .form-group.row
              .col-md-3
                = f.label :last_name, "Last Name", class: "form-control-label"
              .col-md-9
                = f.text_field :last_name, autofocus: true, autocomplete: "off", required:true, placeholder: "Last name", class: "form-control input-text"

            .form-group.row
              .col-md-3
                = f.label :occupation, "Occupation", class: "form-control-label"
              .col-md-9
                = f.text_field :occupation, autofocus: true, autocomplete: "off", required:true, placeholder: "Occupation", class: "form-control input-text"

            .form-group.row
              .col-md-3
                = f.label :phone, "Phone number", class: "form-control-label"
              .col-md-9
                = f.text_field :phone, autofocus: true, autocomplete: "off", required:true, placeholder: "Phone", class: "form-control input-text"

            .form-group.row
              .col-md-3
                = f.label :about, "About me", class: "form-control-label"
              .col-md-9
                = f.text_area :about, placeholder: "About", rows: 4, class: "form-control"

            -if @coach.phone.blank?
              .verify_phone
                = 'Please fill in your profile.'
            - elsif !@coach.validated_phone
              .form-group.row
                .col-md-12
                  = link_to 'Please verify your phone number in order to use the application.', verify_phone_coach_path(@coach), class: "verify_phone"


          .card-footer
            = f.submit "Update", class: "btn btn-sm btn-primary"

app/views/coaches/financial_details.html.haml
.row.pager
  .col-md-12

    = form_tag set_financial_details_coach_path(@coach), method: :post do |f|
      //- add_error(resource.errors.full_messages.to_sentence, 'alert') if resource.errors.present?
      .col-lg-6.col-lg-offset-3
        .card
          .card-header
            %strong Set desired hourly rate
          .card-block
            .form-group
            .form-group.row
              .col-md-3
                = label_tag 'rate', "Desired rate", class: "form-control-label"
              .col-md-9
                = number_field_tag 'rate', @coach.rate,required: true, placeholder: "Rate", min: 10 , max: 200, class: "form-control input-text"

          .card-footer
            = submit_tag "Set", class: "btn btn-sm btn-primary"

app/views/coaches/set_coaching_dates.html.haml
.margin-top-100
.col-lg-6
  = render "coaches/partials/view_coaching_dates"
.col-lg-6
  = render "coaches/partials/set_coaching_dates"

app/views/coaches/show.html.haml
.margin-top-100
.col-lg-6
  = render "coaches/partials/coach_profile", coach: @coach, average_rating: @average_rating
.col-lg-6
  = render "coaches/partials/booking_dates"

app/views/coaches/show_coaches.html.haml
.margin-top-100
- if @coaches.blank?
  .margin-top-100
    .text-center
      %h3
        = "No coaches are available right now. Please try again later."

- else 
  - @coaches.each do |coach| 
    = render "coaches/partials/coach_tile", coach: coach

app/views/coaches/verify_phone.html.haml
.row.pager
  .col-md-12

    = form_tag verify_token_coach_path(@coach), method: :post do |f|
      //- add_error(resource.errors.full_messages.to_sentence, 'alert') if resource.errors.present?
      .col-lg-6.col-lg-offset-3
        .card
          .card-header
            %strong Enter received token
          .card-block
            .form-group.row
              .col-md-12
                = "Please enter the token code receive on your phone."
                

            .form-group.row
              .col-md-3
                = label_tag 'token', "Received token", class: "form-control-label"
              .col-md-9
                = text_field_tag 'token', nil ,required: true, placeholder: "Token", class: "form-control input-text"

            %br
            .form-group.row
              .col-md-12
                = "Didn't receive confirmation token? Click "
                = link_to "here", resend_code_coach_path(@coach), method: :post
                = " to resend." 

          .card-footer
            = submit_tag "Verify", class: "btn btn-sm btn-primary"